# Generated by Django 4.0.4 on 2022-05-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-published',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='published',
        ),
    ]
