# Generated by Django 4.0.4 on 2022-05-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('deportes', 'Deportes'), ('cine', 'Cine'), ('musica', 'Musica'), ('educacion', 'Educacion'), ('politica', 'Politica'), ('recetas', 'Recetas'), ('tecnologia', 'Tecnología')], max_length=50),
        ),
    ]
