# Generated by Django 4.0.4 on 2022-06-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_avatar_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Deportes', 'Deportes'), ('Cine', 'Cine'), ('Música', 'Música'), ('Educación', 'Educación'), ('Politíca', 'Política'), ('Recetas', 'Recetas'), ('Tecnología', 'Tecnología')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
