# Generated by Django 4.0.4 on 2022-06-05 22:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_alter_category_name_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
