# Generated by Django 4.0.4 on 2022-06-05 23:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_alter_post_subtitle_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
